project:
  name:
  dev_version:
  git_repo: <git repo>
production:
  server: <production server ip address>
  url: <production url>
  user: <production ssh deploy user name>
  branch: <git branch>
  deploy_path: <deploy path>
  linked_files:
    - <file to be symlinked from the shared folder>
  linked_dirs:
    - <dir to be symlinked from the shared folder>
staging:
  server: <staging server ip address>
  usl: <staging url>
  user: <staging ssh deploy user name>
  branch: <git branch>
  deploy_path: <deploy path>
  linked_files:
    - <file to be symlinked from the shared folder>
  linked_dirs:
    - <dir to be symlinked from the shared folder>
